baseURL = "https://www.lesamisdepercona.fr/"
languageCode = "fr"
title = "Les amis de Percona"
theme = "ananke"

[params]
    show_reading_time = true
    background_color_class = "bg-dark-blue"
    site_logo = "/img/logo.png"
    favicon = "/img/favicon.png"

[menu]

  [[menu.main]]
    identifier = "Articles"
    name = "Articles"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Qui Sommes Nous?"
    url = "/about/"
    weight = 100

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 200

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

